version: '3.8'

services:
  metrics_mall:
    image: metrics_mall:latest
    container_name: metrics_mall
    restart: on-failure
    ports:
      - "18081:8080"
    env_file:
      - .env
    volumes:
      - ./log/project/metrics_mall:/var/log/metrics_mall:RW
    networks:
      - infrastructure_infrastructure