package lab.zhang.data_science.metrics_mall.integration

import com.fasterxml.jackson.databind.ObjectMapper
import lab.zhang.data_science.metrics_mall.pojo.qo.*
import lab.zhang.data_science.metrics_mall.util.TimeUtil
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.http.MediaType
import org.springframework.test.context.ActiveProfiles
import org.springframework.test.web.servlet.MockMvc
import org.springframework.transaction.annotation.Transactional
import spock.lang.Specification

import static lab.zhang.data_science.metrics_mall.constant.HttpConst.TRACE_ID
import static org.hamcrest.Matchers.not
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status

/**
 * Integration test for Metrics Mall based on INTEGRATION_TEST_PLAN.md
 *
 * This test follows the test plan execution order:
 * 1. Data preparation phase (2.1 - 2.7)
 * 2. Snapshot write phase (3.1 - 3.9)
 * 3. Snapshot query phase (4.1 - 4.5)
 *
 * @author Rongjin Zhang
 * @date 2025-01-16
 */
@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
@Transactional
class MetricsMallIntegrationWriteSnapTest extends Specification {

    @Autowired
    MockMvc mockMvc

    ObjectMapper objectMapper = new ObjectMapper()

    private static final String API_KEY = "test-api-key"
    private static final String ENTITY_CODE = "customer"
    private static final String METRIC_CODE = "consume_amount"
    private static final Long ENTITY_ID = 10000001L

    def getMetricIdByCode(String code) {
        def response = mockMvc.perform(get("/api/v1/metrics/code/${code}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
                .andReturn()
        return objectMapper.readTree(response.response.contentAsString).get("data").get("id").asLong()
    }


    // ==================== 3. 快照写入测试阶段 ====================

    def "3.1 写入快照 - 成功（基础数据）"() {
        given:
        def entityMetaQO = EntityMetaQO.builder()
                .code(ENTITY_CODE)
                .name("顾客")
                .build()
        def metricQO = MetricMetaQO.builder()
                .code(METRIC_CODE)
                .name("消费金额")
                .valueType(2)
                .precision(2)
                .build()
        def entityMetricRelQO = EntityMetricRelQO.builder()
                .entityCode(ENTITY_CODE)
                .metricCode(METRIC_CODE)
                .alias("amount")
                .dataUri("xxx")
                .build()

        def dimensionQO = DimensionQO.builder()
                .code("location")
                .name("地点")
                .build()
        def dimensionQO1 = DimensionQO.builder()
                .code("venues")
                .name("场所")
                .build()
        def dimensionQO2 = DimensionQO.builder()
                .code("category")
                .name("种类")
                .build()
        def metricDimensionRelQO = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("location")
                .isHot(1)
                .validation("xxx")
                .build()
        def metricDimensionRelQO1 = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("venues")
                .isHot(1)
                .validation("xxx")
                .build()
        def metricDimensionRelQO2 = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("category")
                .isHot(1)
                .validation("xxx")
                .build()

        def versionQO11 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(1)
                .calcLogic("xxx")
                .build()
        def versionQO12 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(2)
                .calcLogic("xxx")
                .build()
        def versionQO13 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(3)
                .calcLogic("xxx")
                .build()
        def versionQO14 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(4)
                .calcLogic("xxx")
                .build()
        def versionQO21 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(1)
                .calcLogic("xxx")
                .build()
        def versionQO22 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(2)
                .calcLogic("xxx")
                .build()
        def versionQO23 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(3)
                .calcLogic("xxx")
                .build()
        def versionQO24 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(4)
                .calcLogic("xxx")
                .build()
        def versionQO201 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(1)
                .build()
        // Note: Using code instead of alias as current implementation requires code
        def snapshotQO = MetricSnapshotQO.builder()
                .ec(ENTITY_CODE)
                .eid(ENTITY_ID)
                .metrics([EchoMetricQO.builder()
                                  .code(METRIC_CODE)
                                  .alias("amount")
                                  .v(1)
                                  .value(500.01)
                                  .build()])
                .build()

        when:
        // create metric
        mockMvc.perform(post("/api/v1/entity_metas")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(entityMetaQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metrics")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/entity_metric_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(entityMetricRelQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // relate to dimension
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO1)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO2)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO1)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO2)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        def metricId = getMetricIdByCode(METRIC_CODE)
        // online version 1
        mockMvc.perform(post("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO11)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO12)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO13)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO14)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // online version 2
        mockMvc.perform(post("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO21)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO22)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO23)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO24)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // main version
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO201)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))

        and:
        def response = mockMvc.perform(post("/api/v1/m_snap/write")
                .header("X-API-Key", API_KEY)
                .header(TRACE_ID, TimeUtil.getCurrentTime())
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(snapshotQO)))

        then:
        response.andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
                .andExpect(jsonPath('$.data').exists())
    }

    def "3.1.1 写入快照 - 成功（别名）"() {
        given:
        def entityMetaQO = EntityMetaQO.builder()
                .code(ENTITY_CODE)
                .name("顾客")
                .build()
        def metricQO = MetricMetaQO.builder()
                .code(METRIC_CODE)
                .name("消费金额")
                .valueType(2)
                .precision(2)
                .build()
        def entityMetricRelQO = EntityMetricRelQO.builder()
                .entityCode(ENTITY_CODE)
                .metricCode(METRIC_CODE)
                .alias("amount")
                .dataUri("xxx")
                .build()

        def dimensionQO = DimensionQO.builder()
                .code("location")
                .name("地点")
                .build()
        def dimensionQO1 = DimensionQO.builder()
                .code("venues")
                .name("场所")
                .build()
        def dimensionQO2 = DimensionQO.builder()
                .code("category")
                .name("种类")
                .build()
        def metricDimensionRelQO = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("location")
                .isHot(1)
                .validation("xxx")
                .build()
        def metricDimensionRelQO1 = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("venues")
                .isHot(1)
                .validation("xxx")
                .build()
        def metricDimensionRelQO2 = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("category")
                .isHot(1)
                .validation("xxx")
                .build()

        def versionQO11 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(1)
                .calcLogic("xxx")
                .build()
        def versionQO12 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(2)
                .calcLogic("xxx")
                .build()
        def versionQO13 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(3)
                .calcLogic("xxx")
                .build()
        def versionQO14 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(4)
                .calcLogic("xxx")
                .build()
        def versionQO21 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(1)
                .calcLogic("xxx")
                .build()
        def versionQO22 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(2)
                .calcLogic("xxx")
                .build()
        def versionQO23 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(3)
                .calcLogic("xxx")
                .build()
        def versionQO24 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(4)
                .calcLogic("xxx")
                .build()
        def versionQO201 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(1)
                .build()
        def snapshotQO = MetricSnapshotQO.builder()
                .ec(ENTITY_CODE)
                .eid(ENTITY_ID)
                .metrics([EchoMetricQO.builder()
                                  .alias("amount")
                                  .v(1)
                                  .value(100.0)
                                  .build()])
                .build()

        when:
        // create metric
        mockMvc.perform(post("/api/v1/entity_metas")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(entityMetaQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metrics")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/entity_metric_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(entityMetricRelQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // relate to dimension
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO1)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO2)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO1)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO2)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        def metricId = getMetricIdByCode(METRIC_CODE)
        // online version 1
        mockMvc.perform(post("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO11)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO12)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO13)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO14)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // online version 2
        mockMvc.perform(post("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO21)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO22)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO23)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO24)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // main version
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO201)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))

        and:
        def response = mockMvc.perform(post("/api/v1/m_snap/write")
                .header("X-API-Key", API_KEY)
                .header(TRACE_ID, TimeUtil.getCurrentTime())
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(snapshotQO)))

        then:
        response.andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
                .andExpect(jsonPath('$.data').exists())
    }

    def "3.2 写入快照 - 失败（不支持的别名）"() {
        given:
        def entityMetaQO = EntityMetaQO.builder()
                .code(ENTITY_CODE)
                .name("顾客")
                .build()
        def metricQO = MetricMetaQO.builder()
                .code(METRIC_CODE)
                .name("消费金额")
                .valueType(2)
                .precision(2)
                .build()
        def entityMetricRelQO = EntityMetricRelQO.builder()
                .entityCode(ENTITY_CODE)
                .metricCode(METRIC_CODE)
                .alias("amount")
                .dataUri("xxx")
                .build()

        def dimensionQO = DimensionQO.builder()
                .code("location")
                .name("地点")
                .build()
        def dimensionQO1 = DimensionQO.builder()
                .code("venues")
                .name("场所")
                .build()
        def dimensionQO2 = DimensionQO.builder()
                .code("category")
                .name("种类")
                .build()
        def metricDimensionRelQO = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("location")
                .isHot(1)
                .validation("xxx")
                .build()
        def metricDimensionRelQO1 = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("venues")
                .isHot(1)
                .validation("xxx")
                .build()
        def metricDimensionRelQO2 = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("category")
                .isHot(1)
                .validation("xxx")
                .build()

        def versionQO11 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(1)
                .calcLogic("xxx")
                .build()
        def versionQO12 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(2)
                .calcLogic("xxx")
                .build()
        def versionQO13 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(3)
                .calcLogic("xxx")
                .build()
        def versionQO14 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(4)
                .calcLogic("xxx")
                .build()
        def versionQO21 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(1)
                .calcLogic("xxx")
                .build()
        def versionQO22 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(2)
                .calcLogic("xxx")
                .build()
        def versionQO23 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(3)
                .calcLogic("xxx")
                .build()
        def versionQO24 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(4)
                .calcLogic("xxx")
                .build()
        def versionQO201 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(1)
                .build()
        // Note: Using code instead of alias as current implementation requires code
        def snapshotQO = MetricSnapshotQO.builder()
                .ec(ENTITY_CODE)
                .eid(ENTITY_ID)
                .metrics([EchoMetricQO.builder()
                                  .alias("foo")
                                  .v(1)
                                  .value(100.0)
                                  .build()])
                .build()

        when:
        // create metric
        mockMvc.perform(post("/api/v1/entity_metas")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(entityMetaQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metrics")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/entity_metric_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(entityMetricRelQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // relate to dimension
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO1)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO2)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO1)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO2)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        def metricId = getMetricIdByCode(METRIC_CODE)
        // online version 1
        mockMvc.perform(post("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO11)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO12)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO13)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO14)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // online version 2
        mockMvc.perform(post("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO21)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO22)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO23)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO24)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // main version
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO201)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))

        and:
        def response = mockMvc.perform(post("/api/v1/m_snap/write")
                .header("X-API-Key", API_KEY)
                .header(TRACE_ID, TimeUtil.getCurrentTime())
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(snapshotQO)))

        then:
        response.andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(not(0)))
    }

    def "3.3 写入快照 - 失败（不存在的版本）"() {
        given:
        def entityMetaQO = EntityMetaQO.builder()
                .code(ENTITY_CODE)
                .name("顾客")
                .build()
        def metricQO = MetricMetaQO.builder()
                .code(METRIC_CODE)
                .name("消费金额")
                .valueType(2)
                .precision(2)
                .build()
        def entityMetricRelQO = EntityMetricRelQO.builder()
                .entityCode(ENTITY_CODE)
                .metricCode(METRIC_CODE)
                .alias("amount")
                .dataUri("xxx")
                .build()

        def dimensionQO = DimensionQO.builder()
                .code("location")
                .name("地点")
                .build()
        def dimensionQO1 = DimensionQO.builder()
                .code("venues")
                .name("场所")
                .build()
        def dimensionQO2 = DimensionQO.builder()
                .code("category")
                .name("种类")
                .build()
        def metricDimensionRelQO = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("location")
                .isHot(1)
                .validation("xxx")
                .build()
        def metricDimensionRelQO1 = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("venues")
                .isHot(1)
                .validation("xxx")
                .build()
        def metricDimensionRelQO2 = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("category")
                .isHot(1)
                .validation("xxx")
                .build()

        def versionQO11 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(1)
                .calcLogic("xxx")
                .build()
        def versionQO12 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(2)
                .calcLogic("xxx")
                .build()
        def versionQO13 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(3)
                .calcLogic("xxx")
                .build()
        def versionQO14 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(4)
                .calcLogic("xxx")
                .build()
        def versionQO21 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(1)
                .calcLogic("xxx")
                .build()
        def versionQO22 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(2)
                .calcLogic("xxx")
                .build()
        def versionQO23 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(3)
                .calcLogic("xxx")
                .build()
        def versionQO24 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(4)
                .calcLogic("xxx")
                .build()
        def versionQO201 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(1)
                .build()
        // Note: Using code instead of alias as current implementation requires code
        def snapshotQO = MetricSnapshotQO.builder()
                .ec(ENTITY_CODE)
                .eid(ENTITY_ID)
                .metrics([EchoMetricQO.builder()
                                  .code(METRIC_CODE)
                                  .alias("amount")
                                  .v(3)
                                  .value(100)
                                  .build()])
                .build()

        when:
        // create metric
        mockMvc.perform(post("/api/v1/entity_metas")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(entityMetaQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metrics")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/entity_metric_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(entityMetricRelQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // relate to dimension
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO1)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO2)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO1)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO2)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        def metricId = getMetricIdByCode(METRIC_CODE)
        // online version 1
        mockMvc.perform(post("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO11)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO12)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO13)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO14)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // online version 2
        mockMvc.perform(post("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO21)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO22)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO23)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO24)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // main version
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO201)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))

        and:
        def response = mockMvc.perform(post("/api/v1/m_snap/write")
                .header("X-API-Key", API_KEY)
                .header(TRACE_ID, TimeUtil.getCurrentTime())
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(snapshotQO)))

        then:
        response.andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(not(0)))
    }

    def "3.4 写入快照 - 失败（不存在的维度）"() {
        given:
        def entityMetaQO = EntityMetaQO.builder()
                .code(ENTITY_CODE)
                .name("顾客")
                .build()
        def metricQO = MetricMetaQO.builder()
                .code(METRIC_CODE)
                .name("消费金额")
                .valueType(2)
                .precision(2)
                .build()
        def entityMetricRelQO = EntityMetricRelQO.builder()
                .entityCode(ENTITY_CODE)
                .metricCode(METRIC_CODE)
                .alias("amount")
                .dataUri("xxx")
                .build()

        def dimensionQO = DimensionQO.builder()
                .code("location")
                .name("地点")
                .build()
        def dimensionQO1 = DimensionQO.builder()
                .code("venues")
                .name("场所")
                .build()
        def dimensionQO2 = DimensionQO.builder()
                .code("category")
                .name("种类")
                .build()
        def metricDimensionRelQO = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("location")
                .isHot(1)
                .validation("xxx")
                .build()
        def metricDimensionRelQO1 = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("venues")
                .isHot(1)
                .validation("xxx")
                .build()
        def metricDimensionRelQO2 = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("category")
                .isHot(1)
                .validation("xxx")
                .build()

        def versionQO11 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(1)
                .calcLogic("xxx")
                .build()
        def versionQO12 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(2)
                .calcLogic("xxx")
                .build()
        def versionQO13 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(3)
                .calcLogic("xxx")
                .build()
        def versionQO14 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(4)
                .calcLogic("xxx")
                .build()
        def versionQO21 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(1)
                .calcLogic("xxx")
                .build()
        def versionQO22 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(2)
                .calcLogic("xxx")
                .build()
        def versionQO23 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(3)
                .calcLogic("xxx")
                .build()
        def versionQO24 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(4)
                .calcLogic("xxx")
                .build()
        def versionQO201 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(1)
                .build()
        // Note: Using code instead of alias as current implementation requires code
        def snapshotQO = MetricSnapshotQO.builder()
                .ec(ENTITY_CODE)
                .eid(ENTITY_ID)
                .metrics([EchoMetricQO.builder()
                                  .code(METRIC_CODE)
                                  .alias("amount")
                                  .v(1)
                                  .dims(["time": "8000"])
                                  .value(100)
                                  .build()])
                .build()

        when:
        // create metric
        mockMvc.perform(post("/api/v1/entity_metas")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(entityMetaQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metrics")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/entity_metric_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(entityMetricRelQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // relate to dimension
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO1)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO2)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO1)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO2)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        def metricId = getMetricIdByCode(METRIC_CODE)
        // online version 1
        mockMvc.perform(post("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO11)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO12)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO13)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO14)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // online version 2
        mockMvc.perform(post("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO21)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO22)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO23)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO24)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // main version
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO201)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))

        and:
        def response = mockMvc.perform(post("/api/v1/m_snap/write")
                .header("X-API-Key", API_KEY)
                .header(TRACE_ID, TimeUtil.getCurrentTime())
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(snapshotQO)))

        then:
        response.andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(not(0)))
    }

    def "3.5 写入快照 - 成功（带单个维度）"() {
        given:
        def entityMetaQO = EntityMetaQO.builder()
                .code(ENTITY_CODE)
                .name("顾客")
                .build()
        def metricQO = MetricMetaQO.builder()
                .code(METRIC_CODE)
                .name("消费金额")
                .valueType(2)
                .precision(2)
                .build()
        def entityMetricRelQO = EntityMetricRelQO.builder()
                .entityCode(ENTITY_CODE)
                .metricCode(METRIC_CODE)
                .alias("amount")
                .dataUri("xxx")
                .build()

        def dimensionQO = DimensionQO.builder()
                .code("location")
                .name("地点")
                .build()
        def dimensionQO1 = DimensionQO.builder()
                .code("venues")
                .name("场所")
                .build()
        def dimensionQO2 = DimensionQO.builder()
                .code("category")
                .name("种类")
                .build()
        def metricDimensionRelQO = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("location")
                .isHot(1)
                .validation("xxx")
                .build()
        def metricDimensionRelQO1 = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("venues")
                .isHot(1)
                .validation("xxx")
                .build()
        def metricDimensionRelQO2 = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("category")
                .isHot(1)
                .validation("xxx")
                .build()

        def versionQO11 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(1)
                .calcLogic("xxx")
                .build()
        def versionQO12 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(2)
                .calcLogic("xxx")
                .build()
        def versionQO13 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(3)
                .calcLogic("xxx")
                .build()
        def versionQO14 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(4)
                .calcLogic("xxx")
                .build()
        def versionQO21 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(1)
                .calcLogic("xxx")
                .build()
        def versionQO22 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(2)
                .calcLogic("xxx")
                .build()
        def versionQO23 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(3)
                .calcLogic("xxx")
                .build()
        def versionQO24 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(4)
                .calcLogic("xxx")
                .build()
        def versionQO201 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(1)
                .build()
        // Note: Using code instead of alias as current implementation requires code
        def snapshotQO = MetricSnapshotQO.builder()
                .ec(ENTITY_CODE)
                .eid(ENTITY_ID)
                .metrics([EchoMetricQO.builder()
                                  .code(METRIC_CODE)
                                  .alias("amount")
                                  .v(1)
                                  .dims(["location": "beijing"])
                                  .value(99.99)
                                  .build()])
                .build()

        when:
        // create metric
        mockMvc.perform(post("/api/v1/entity_metas")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(entityMetaQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metrics")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/entity_metric_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(entityMetricRelQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // relate to dimension
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO1)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO2)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO1)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO2)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        def metricId = getMetricIdByCode(METRIC_CODE)
        // online version 1
        mockMvc.perform(post("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO11)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO12)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO13)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO14)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // online version 2
        mockMvc.perform(post("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO21)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO22)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO23)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO24)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // main version
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO201)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))

        and:
        def response = mockMvc.perform(post("/api/v1/m_snap/write")
                .header("X-API-Key", API_KEY)
                .header(TRACE_ID, TimeUtil.getCurrentTime())
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(snapshotQO)))

        then:
        response.andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
                .andExpect(jsonPath('$.data').exists())
    }

    def "3.6 写入快照 - 成功（带两个维度）"() {
        given:
        def entityMetaQO = EntityMetaQO.builder()
                .code(ENTITY_CODE)
                .name("顾客")
                .build()
        def metricQO = MetricMetaQO.builder()
                .code(METRIC_CODE)
                .name("消费金额")
                .valueType(2)
                .precision(2)
                .build()
        def entityMetricRelQO = EntityMetricRelQO.builder()
                .entityCode(ENTITY_CODE)
                .metricCode(METRIC_CODE)
                .alias("amount")
                .dataUri("xxx")
                .build()

        def dimensionQO = DimensionQO.builder()
                .code("location")
                .name("地点")
                .build()
        def dimensionQO1 = DimensionQO.builder()
                .code("venues")
                .name("场所")
                .build()
        def dimensionQO2 = DimensionQO.builder()
                .code("category")
                .name("种类")
                .build()
        def metricDimensionRelQO = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("location")
                .isHot(1)
                .validation("xxx")
                .build()
        def metricDimensionRelQO1 = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("venues")
                .isHot(1)
                .validation("xxx")
                .build()
        def metricDimensionRelQO2 = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("category")
                .isHot(1)
                .validation("xxx")
                .build()
        def metricDimensinGroupRelQO = MetricDimensionGroupRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCodes("location,venues")
                .build()

        def versionQO11 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(1)
                .calcLogic("xxx")
                .build()
        def versionQO12 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(2)
                .calcLogic("xxx")
                .build()
        def versionQO13 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(3)
                .calcLogic("xxx")
                .build()
        def versionQO14 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(4)
                .calcLogic("xxx")
                .build()
        def versionQO21 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(1)
                .calcLogic("xxx")
                .build()
        def versionQO22 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(2)
                .calcLogic("xxx")
                .build()
        def versionQO23 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(3)
                .calcLogic("xxx")
                .build()
        def versionQO24 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(4)
                .calcLogic("xxx")
                .build()
        def versionQO201 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(1)
                .build()
        // Note: Using code instead of alias as current implementation requires code
        def snapshotQO = MetricSnapshotQO.builder()
                .ec(ENTITY_CODE)
                .eid(ENTITY_ID)
                .metrics([EchoMetricQO.builder()
                                  .code(METRIC_CODE)
                                  .alias("amount")
                                  .v(1)
                                  .dims(["location": "shanghai", "venues": "hotel"])
                                  .value(400.02)
                                  .build()])
                .build()

        when:
        // create metric
        mockMvc.perform(post("/api/v1/entity_metas")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(entityMetaQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metrics")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        def metricId = getMetricIdByCode(METRIC_CODE)
        mockMvc.perform(post("/api/v1/entity_metric_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(entityMetricRelQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // relate to dimension
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO1)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO2)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO1)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO2)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // relate to dimension group
        mockMvc.perform(post("/api/v1/metric_dim_group_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensinGroupRelQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // online version 1
        mockMvc.perform(post("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO11)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO12)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO13)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO14)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // online version 2
        mockMvc.perform(post("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO21)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO22)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO23)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO24)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // main version
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO201)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))

        and:
        def response = mockMvc.perform(post("/api/v1/m_snap/write")
                .header("X-API-Key", API_KEY)
                .header(TRACE_ID, TimeUtil.getCurrentTime())
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(snapshotQO)))

        then:
        response.andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
                .andExpect(jsonPath('$.data').exists())
    }

    def "3.7 写入快照 - 失败（不支持的维度组合）"() {
        given:
        def entityMetaQO = EntityMetaQO.builder()
                .code(ENTITY_CODE)
                .name("顾客")
                .build()
        def metricQO = MetricMetaQO.builder()
                .code(METRIC_CODE)
                .name("消费金额")
                .valueType(2)
                .precision(2)
                .build()
        def entityMetricRelQO = EntityMetricRelQO.builder()
                .entityCode(ENTITY_CODE)
                .metricCode(METRIC_CODE)
                .alias("amount")
                .dataUri("xxx")
                .build()

        def dimensionQO = DimensionQO.builder()
                .code("location")
                .name("地点")
                .build()
        def dimensionQO1 = DimensionQO.builder()
                .code("venues")
                .name("场所")
                .build()
        def dimensionQO2 = DimensionQO.builder()
                .code("category")
                .name("种类")
                .build()
        def metricDimensionRelQO = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("location")
                .isHot(1)
                .validation("xxx")
                .build()
        def metricDimensionRelQO1 = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("venues")
                .isHot(1)
                .validation("xxx")
                .build()
        def metricDimensionRelQO2 = MetricDimensionRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCode("category")
                .isHot(1)
                .validation("xxx")
                .build()
        def metricDimensinGroupRelQO = MetricDimensionGroupRelQO.builder()
                .metricCode(METRIC_CODE)
                .dimensionCodes("location,venues")
                .build()

        def versionQO11 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(1)
                .calcLogic("xxx")
                .build()
        def versionQO12 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(2)
                .calcLogic("xxx")
                .build()
        def versionQO13 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(3)
                .calcLogic("xxx")
                .build()
        def versionQO14 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(1)
                .isMain(0)
                .lifeStatus(4)
                .calcLogic("xxx")
                .build()
        def versionQO21 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(1)
                .calcLogic("xxx")
                .build()
        def versionQO22 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(2)
                .calcLogic("xxx")
                .build()
        def versionQO23 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(3)
                .calcLogic("xxx")
                .build()
        def versionQO24 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(0)
                .lifeStatus(4)
                .calcLogic("xxx")
                .build()
        def versionQO201 = MetricVersionQO.builder()
                .metricCode(METRIC_CODE)
                .version(2)
                .isMain(1)
                .build()
        // Note: Using code instead of alias as current implementation requires code
        def snapshotQO = MetricSnapshotQO.builder()
                .ec(ENTITY_CODE)
                .eid(ENTITY_ID)
                .metrics([EchoMetricQO.builder()
                                  .code(METRIC_CODE)
                                  .alias("amount")
                                  .v(1)
                                  .dims(["location": "shanghai", "venues": "hotel", "category": "food"])
                                  .value(100.0)
                                  .build()])
                .build()

        when:
        // create metric
        mockMvc.perform(post("/api/v1/entity_metas")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(entityMetaQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metrics")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        def metricId = getMetricIdByCode(METRIC_CODE)
        mockMvc.perform(post("/api/v1/entity_metric_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(entityMetricRelQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // relate to dimension
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO1)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/dims")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dimensionQO2)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO1)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(post("/api/v1/metric_dim_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensionRelQO2)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // relate to dimension group
        mockMvc.perform(post("/api/v1/metric_dim_group_rels")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(metricDimensinGroupRelQO)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // online version 1
        mockMvc.perform(post("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO11)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO12)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO13)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO14)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // online version 2
        mockMvc.perform(post("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO21)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO22)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO23)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO24)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))
        // main version
        mockMvc.perform(put("/api/v1/metrics/${metricId}/versions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(versionQO201)))
                .andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(0))

        and:
        def response = mockMvc.perform(post("/api/v1/m_snap/write")
                .header("X-API-Key", API_KEY)
                .header(TRACE_ID, TimeUtil.getCurrentTime())
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(snapshotQO)))

        then:
        response.andExpect(status().isOk())
                .andExpect(jsonPath('$.code').value(not(0)))
    }
}
